/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javapos;

import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class JavaPOS1 extends javax.swing.JFrame {

    /**
     * Creates new form JavaPOS1
     */
    public JavaPOS1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnHoneyChicken = new javax.swing.JButton();
        jbtnHoneyFish = new javax.swing.JButton();
        jBtnRicaChic = new javax.swing.JButton();
        jBtnMcNuggets = new javax.swing.JButton();
        jBtnFrenchFries = new javax.swing.JButton();
        jBtnChichkenWrap = new javax.swing.JButton();
        jBtnFishWrap = new javax.swing.JButton();
        jBtnHappyMeal3 = new javax.swing.JButton();
        jBtnFantaFloat = new javax.swing.JButton();
        jBtnICJFloat = new javax.swing.JButton();
        jBtnICJelly = new javax.swing.JButton();
        jBtnCokeFloat = new javax.swing.JButton();
        jBtnHappyMeal1 = new javax.swing.JButton();
        jBtnHappyMeal2 = new javax.swing.JButton();
        jBtnRicaFish = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtn6 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jPanel36 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtChange = new javax.swing.JTextField();
        jtxtDisplay = new javax.swing.JTextField();
        jcboPayment = new javax.swing.JComboBox<>();
        jPanel44 = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();
        jPanel51 = new javax.swing.JPanel();
        jtxtBarCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnHoneyChicken.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jbtnHoneyChicken.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Honey Garlic Chih.png"))); // NOI18N
        jbtnHoneyChicken.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnHoneyChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHoneyChickenActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnHoneyChicken, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 120));

        jbtnHoneyFish.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jbtnHoneyFish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Honey Garlic Fish.png"))); // NOI18N
        jbtnHoneyFish.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnHoneyFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHoneyFishActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnHoneyFish, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 140, 120));

        jBtnRicaChic.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jBtnRicaChic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Rica Rica.png"))); // NOI18N
        jBtnRicaChic.setAutoscrolls(true);
        jBtnRicaChic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnRicaChic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRicaChicActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnRicaChic, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 140, 120));

        jBtnMcNuggets.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jBtnMcNuggets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/McNuggets.png"))); // NOI18N
        jBtnMcNuggets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcNuggetsActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnMcNuggets, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 140, 120));

        jBtnFrenchFries.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jBtnFrenchFries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/FF.png"))); // NOI18N
        jBtnFrenchFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFrenchFriesActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnFrenchFries, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 140, 120));

        jBtnChichkenWrap.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jBtnChichkenWrap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Chicken Snack Wrap.png"))); // NOI18N
        jBtnChichkenWrap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnChichkenWrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnChichkenWrapActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnChichkenWrap, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 140, 120));

        jBtnFishWrap.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jBtnFishWrap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Fish Snack Wrap.png"))); // NOI18N
        jBtnFishWrap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnFishWrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFishWrapActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnFishWrap, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, 120));

        jBtnHappyMeal3.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jBtnHappyMeal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/3.png"))); // NOI18N
        jBtnHappyMeal3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnHappyMeal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHappyMeal3ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnHappyMeal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 140, 120));

        jBtnFantaFloat.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jBtnFantaFloat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Fanta McFloat.png"))); // NOI18N
        jBtnFantaFloat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFantaFloatActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnFantaFloat, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 140, 120));

        jBtnICJFloat.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jBtnICJFloat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/IC Jelly float.png"))); // NOI18N
        jBtnICJFloat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnICJFloatActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnICJFloat, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 140, 120));

        jBtnICJelly.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jBtnICJelly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/IC Jelly.png"))); // NOI18N
        jBtnICJelly.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnICJelly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnICJellyActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnICJelly, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 140, 120));

        jBtnCokeFloat.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jBtnCokeFloat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/McFloat.png"))); // NOI18N
        jBtnCokeFloat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCokeFloatActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCokeFloat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 140, 120));

        jBtnHappyMeal1.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jBtnHappyMeal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1.png"))); // NOI18N
        jBtnHappyMeal1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnHappyMeal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHappyMeal1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnHappyMeal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 140, 120));

        jBtnHappyMeal2.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jBtnHappyMeal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/2.png"))); // NOI18N
        jBtnHappyMeal2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnHappyMeal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHappyMeal2ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnHappyMeal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 140, 120));

        jBtnRicaFish.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jBtnRicaFish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Rica Rica Fish.png"))); // NOI18N
        jBtnRicaFish.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnRicaFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRicaFishActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnRicaFish, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 140, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 730, 400));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn6.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 80, 90));

        jbtn9.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 80, 90));

        jbtn7.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 90));

        jbtn4.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, 90));

        jbtn5.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 80, 90));

        jbtnC.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 80, 90));

        jbtnDot.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 80, 90));

        jbtn0.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 80, 90));

        jbtn1.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 80, 90));

        jbtn2.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 80, 90));

        jbtn3.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 80, 90));

        jbtn8.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 80, 90));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 400));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 370, 320));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel12.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel16.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel12.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel20.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel24.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel26.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel24.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel20.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jbtnReset.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel20.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 180, 50));

        jbtnPay.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel20.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 180, 50));

        jbtnPrint.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel20.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 180, 50));

        jbtnRemove.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel20.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 180, 50));

        jbtnExit.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel20.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 370, 50));

        jPanel12.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 440, 170));

        jPanel28.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel28.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel30.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel31.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel30.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel28.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel32.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel33.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel32.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel34.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel35.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel34.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel32.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel28.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Total");
        jPanel28.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel2.setText("Sub Total");
        jPanel28.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel3.setText("Pajak");
        jPanel28.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jtxtTotal.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });
        jPanel28.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 260, 40));

        jtxtSubTotal.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jtxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubTotalActionPerformed(evt);
            }
        });
        jPanel28.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 260, 40));

        jtxtTax.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });
        jPanel28.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 260, 40));

        jPanel12.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 170));

        jPanel36.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel37.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel36.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel38.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel39.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel38.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel36.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel40.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel40.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel41.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel40.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel42.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel42.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel43.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel43.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel42.add(jPanel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel40.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel36.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel4.setText("Change");
        jPanel36.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel5.setText("Cash");
        jPanel36.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel6.setText("Payment Method");
        jPanel36.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jtxtChange.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jtxtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChangeActionPerformed(evt);
            }
        });
        jPanel36.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 200, 40));

        jtxtDisplay.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });
        jPanel36.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 200, 40));

        jcboPayment.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jcboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Ovo, Gopay, SPay", "Dana", " " }));
        jcboPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboPaymentActionPerformed(evt);
            }
        });
        jPanel36.add(jcboPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 200, 40));

        jPanel12.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 440, 170));

        jPanel44.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel44.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel45.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel45.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel44.add(jPanel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel46.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel46.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel47.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel47.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel46.add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel44.add(jPanel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel48.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel48.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel49.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel49.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel48.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel50.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel50.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel51.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel51.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel50.add(jPanel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel48.add(jPanel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel44.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jPanel12.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 130));

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1380, 230));

        jtxtBarCode.setFont(new java.awt.Font("Code39", 0, 36)); // NOI18N
        jtxtBarCode.setForeground(new java.awt.Color(0, 0, 0));
        jtxtBarCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBarCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBarCodeActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 370, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//================ FUNCTION for CALCULATE ITEM AND TOTAL PRICE =================
    public void ItemCost()
    {
        double sum = 0;
        
        for (int i = 0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        jtxtSubTotal.setText(Double.toString(sum));
        double cTotal1 = Double.parseDouble(jtxtSubTotal.getText());
        
        double cTax = (cTotal1 * 3.9)/ 100;
        String iTaxTotal = String.format("£ %.2f", cTax);
        jtxtTax.setText(iTaxTotal);
        
        String iSubTotal = String.format("£ %.2f", cTotal1);
        jtxtSubTotal.setText(iSubTotal);
        
        String iTotal = String.format("£ %.2f", cTotal1 + cTax);
        jtxtTotal.setText(iTotal);
        
        String BarCode = String.format("Total is %.2f", cTotal1 + cTax );
        jtxtBarCode.setText(BarCode);
    }
    
//================================ FUNCTION for CHANGE =========================
    public void Change()
    {
        double sum = 0;
        double tax =3.9;
        double cash = Double.parseDouble(jtxtDisplay.getText());
        
        for (int i = 0; i < jTable1.getRowCount(); i ++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        
        double cTax = ((sum * 3.9)/100);
        double cChange = (cash - (sum + cTax));
        
        String Given = String.format("£ %.2f",cChange);
        jtxtChange.setText(Given) ;
    }
    
    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn6.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn6.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn9.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn9.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn7.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn7.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn4.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn4.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn5.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn5.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        jtxtDisplay.setText("");
        jtxtChange.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
        
        if(! jtxtDisplay.getText().contains("."))
        {
            jtxtDisplay.setText(jtxtDisplay.getText() + jbtnDot.getText());
        }
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn0.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn0.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn1.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn1.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn2.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn2.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn3.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn3.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn8.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn8.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtnHoneyFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHoneyFishActionPerformed
        double PriceOfItem = 3.40;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Honey Garlic Fish Rice", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnHoneyFishActionPerformed

    private void jBtnRicaChicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRicaChicActionPerformed
        double PriceOfItem = 3.25;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Rica Rica Chicken Rice", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jBtnRicaChicActionPerformed

    private void jBtnMcNuggetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcNuggetsActionPerformed
        double PriceOfItem = 2.15;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"McNuggets", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jBtnMcNuggetsActionPerformed

    private void jBtnFrenchFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFrenchFriesActionPerformed
        double PriceOfItem = 2.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"French Fries", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jBtnFrenchFriesActionPerformed

    private void jBtnChichkenWrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnChichkenWrapActionPerformed
        double PriceOfItem = 2.35;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Chicken Snack Wrap", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jBtnChichkenWrapActionPerformed

    private void jBtnFishWrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFishWrapActionPerformed
        double PriceOfItem = 2.35;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Fish Snack Wrap", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jBtnFishWrapActionPerformed

    private void jBtnFantaFloatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFantaFloatActionPerformed
        double PriceOfItem = 1.55;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Fanta McFloat", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jBtnFantaFloatActionPerformed

    private void jBtnICJFloatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnICJFloatActionPerformed
        double PriceOfItem = 1.55;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Ice Coffee Jelly Float", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jBtnICJFloatActionPerformed

    private void jBtnICJellyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnICJellyActionPerformed
        double PriceOfItem = 1.35;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Ice Coffee Jelly", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jBtnICJellyActionPerformed

    private void jBtnCokeFloatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCokeFloatActionPerformed
        double PriceOfItem = 1.55;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Coke McFloat", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jBtnCokeFloatActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jtxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalActionPerformed

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed

    private void jtxtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChangeActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void jcboPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboPaymentActionPerformed

    private void jtxtBarCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBarCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBarCodeActionPerformed

private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to EXIT", "Point of Sale", 
                JOptionPane.YES_NO_OPTION ) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnHoneyChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHoneyChickenActionPerformed
        
        double PriceOfItem = 3.40;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Honey Garlic Chicken Rice", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnHoneyChickenActionPerformed

    private void jBtnRicaFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRicaFishActionPerformed
        double PriceOfItem = 3.25;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Rica Rica Fish Rice", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jBtnRicaFishActionPerformed

    private void jBtnHappyMeal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHappyMeal3ActionPerformed
        double PriceOfItem = 5.40;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Happy Meal Ayam", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jBtnHappyMeal3ActionPerformed

    private void jBtnHappyMeal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHappyMeal2ActionPerformed
        double PriceOfItem = 5.40;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Happy Meal Chicken Burger", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jBtnHappyMeal2ActionPerformed

    private void jBtnHappyMeal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHappyMeal1ActionPerformed
        double PriceOfItem = 5.40;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Happy Meal McNuggets", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jBtnHappyMeal1ActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
        if (jcboPayment.getSelectedItem().equals("Cash"))
            {
                Change();
            }
            else
            {
                jtxtChange.setText("");
                jtxtDisplay.setText("");
            }
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtSubTotal.setText("");
        jtxtDisplay.setText("");
        jtxtBarCode.setText("");
        
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        
        MessageFormat header = new MessageFormat("Receipt of Ms Abigail");
        MessageFormat footer = new MessageFormat("page {0, number, integer}");
        
        try
        {
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        }
        
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("No printer found", e.getMessage());
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        int RemoveItem = jTable1.getSelectedColumn();
        if( RemoveItem >= 0)
        {
            model.removeRow(RemoveItem);
        }
        
        ItemCost(); 
        
        if (jcboPayment.getSelectedItem().equals("Cash"))
            {
            Change();
            }
            else 
            {
            jtxtChange.setText("");
            jtxtDisplay.setText("");
            }   
    }//GEN-LAST:event_jbtnRemoveActionPerformed
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaPOS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaPOS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaPOS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaPOS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaPOS1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnChichkenWrap;
    private javax.swing.JButton jBtnCokeFloat;
    private javax.swing.JButton jBtnFantaFloat;
    private javax.swing.JButton jBtnFishWrap;
    private javax.swing.JButton jBtnFrenchFries;
    private javax.swing.JButton jBtnHappyMeal1;
    private javax.swing.JButton jBtnHappyMeal2;
    private javax.swing.JButton jBtnHappyMeal3;
    private javax.swing.JButton jBtnICJFloat;
    private javax.swing.JButton jBtnICJelly;
    private javax.swing.JButton jBtnMcNuggets;
    private javax.swing.JButton jBtnRicaChic;
    private javax.swing.JButton jBtnRicaFish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnHoneyChicken;
    private javax.swing.JButton jbtnHoneyFish;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JComboBox<String> jcboPayment;
    private javax.swing.JTextField jtxtBarCode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
